/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomutual.Vistas;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

 

public class Menu extends javax.swing.JFrame {

 
    
    public Menu() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        //ImageIcon icono= new ImageIcon(getClass().getResource("/Imagenes/Image800.png"));
        //Image miImagen=icono.getImage();
        Escritorio = new javax.swing.JDesktopPane();
        jLBanner = new javax.swing.JLabel();
        jPInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBSalir = new javax.swing.JButton();
        jBIngresar = new javax.swing.JButton();
        //ImageIcon icono=new ImageIcon(getClass().getResource("/Imagenes/Image800.png"));
        //Image miImagen=icono.getImage();
        jPFondo = new javax.swing.JPanel();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 515));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Escritorio.setBackground(new java.awt.Color(255, 255, 255));
        Escritorio.setToolTipText("X");
        Escritorio.setPreferredSize(new java.awt.Dimension(900, 515));
        Escritorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Banner 900x100.png"))); // NOI18N
        Escritorio.add(jLBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 906, -1));

        jPInicio.setBackground(new java.awt.Color(153, 255, 153));
        jPInicio.setPreferredSize(new java.awt.Dimension(229, 800));
        jPInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo Mutual.png"))); // NOI18N
        jPInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 230, 240));

        jBSalir.setBackground(new java.awt.Color(0, 102, 102));
        jBSalir.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 18)); // NOI18N
        jBSalir.setForeground(new java.awt.Color(204, 255, 204));
        jBSalir.setText("Salir");
        jPInicio.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 210, 60));

        jBIngresar.setBackground(new java.awt.Color(0, 102, 102));
        jBIngresar.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 18)); // NOI18N
        jBIngresar.setForeground(new java.awt.Color(204, 255, 204));
        jBIngresar.setText("Ingresar");
        jPInicio.add(jBIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 60));

        Escritorio.add(jPInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 101, -1, 410));

        jPFondo.setPreferredSize(new java.awt.Dimension(671, 415));

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImageFondo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPFondoLayout = new javax.swing.GroupLayout(jPFondo);
        jPFondo.setLayout(jPFondoLayout);
        jPFondoLayout.setHorizontalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        jPFondoLayout.setVerticalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        Escritorio.add(jPFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 670, 410));

        getContentPane().add(Escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 515));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JButton jBIngresar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLBanner;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPFondo;
    private javax.swing.JPanel jPInicio;
    // End of variables declaration//GEN-END:variables
}
