/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomutual.Vistas;

/**
 *
 * @author sonia
 */
public class PanelPrestadores extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrestadores
     */
    public PanelPrestadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPruebaVistaPrestadores = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPruebaVistaPrestadores.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPruebaVistaPrestadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPruebaVistaPrestadores.setText("VISTA PRESTADORES");
        add(jLabelPruebaVistaPrestadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 270, 140));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelPruebaVistaPrestadores;
    // End of variables declaration//GEN-END:variables
}
